name: identity_firebase_google
description: Google SSO by Firebase for Identity package
version: 0.1.1
author: Long Do <me@dotronglong.com>
homepage: https://github.com/dotronglong/dart-identity-firebase-google

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sso: ^0.1.0
  identity: ^0.1.0
  identity_firebase: ^0.1.0
  firebase_auth: ^0.15.3
  google_sign_in: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - images/google.png
